### ISSUE TITLE
[1.19.2 - 2.4.1] Issue in Multiplayer regarding grindstone polishing recipes

### ISSUE THREAD

**Issue by SiverDX** [Uraneptus/Sullys-Mod#68]
I get disconnected when trying to join the server

I don't have any custom recipes
Do the fallbacks in the `fromJson` also properly apply to the `fromNetwork` (I don't know how recipes work in that regard)?
(Since the recipes you provide are missing some of the fields it would try to read here)

``` log
[28Sep2023 07:55:42.739] [Netty Play IO Thread #3/ERROR] [com.mrbysco.spititout.SpitItOut/]: Exception caught in connection handler!
 io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: malformed input around byte 2
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_130081_(FriendlyByteBuf.java:514)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_130260_(FriendlyByteBuf.java:494)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_130267_(FriendlyByteBuf.java:554)
	at TRANSFORMER/sullysmod@2.4.1-beta/com.uraneptus.sullysmod.common.recipes.GrindstonePolishingRecipe$Serializer.fromNetwork(GrindstonePolishingRecipe.java:148)
	at TRANSFORMER/sullysmod@2.4.1-beta/com.uraneptus.sullysmod.common.recipes.GrindstonePolishingRecipe$Serializer.m_8005_(GrindstonePolishingRecipe.java:106)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:45)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_236838_(FriendlyByteBuf.java:152)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_236845_(FriendlyByteBuf.java:168)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:433)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:485)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:32)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.codec@4.1.77.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.handler@4.1.77.Final/io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.UTFDataFormatException: malformed input around byte 2
	at java.base/java.io.DataInputStream.readUTF(Unknown Source)
	at MC-BOOTSTRAP/io.netty.buffer@4.1.77.Final/io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:301)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:275)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:225)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.FriendlyByteBuf.m_130081_(FriendlyByteBuf.java:512)
	... 48 more
```

**Comment by Uraneptus** [comment]
Thank you for reporting this!
So you don't have any custom recipes on your client and on your server, right?
And this crash is happening when you join the server?
Just asking to clearly this again for better debugging.
I will look into it later today!

**Comment by SiverDX** [comment]
It's not really a crash, I just get disconnected when trying to join
(Works fine in Singleplayer)

I did not create any recipes myself and the only mod which references `sullysmod` is `Spelunkery`
(Which is using its own grindstone polishing recipe)

**Comment by Uraneptus** [comment]
Alright, figured out why this happened. Again, thank you for reporting this! ^^
The fix will be released in an update soon
